name: Build project

on: [push, pull_request]  

jobs:
    buildForAllSupportedPlatforms:
        name: Build for ${{ matrix.targetPlatform }}
        
        runs-on: [ubuntu-latest]
        strategy:
            fail-fast: false
            matrix:
                targetPlatform:
                    - StandaloneWindows64 # Build a Windows 64-bit standalone.
        steps:
            - uses: actions/checkout@v2
              with:
                  fetch-depth: 0
                  lfs: true
            - uses: actions/cache@v2
              with:
                  path: Library
                  key: Library-${{ matrix.targetPlatform }}
                  restore-keys: Library-


            - name: Build image busybox
              run: |
                docker build -t test_image:latest -<<EOF
                FROM busybox
                RUN touch abc.txt
                EOF

            - name: Build image Windows64
              run: |
                docker build -t testwin64_image:latest -<<EOF
                #Win11
                FROM mcr.microsoft.com/windows/servercore/insider:10.0.20348.1
                cd "C:\Program Files\Docker\Docker"
                ./DockerCli.exe -SwitchDaemon

                #input GitHub runner version argument
                ARG RUNNER_VERSION

                LABEL Author="Velu Demo"
                LABEL Email="velujay@gmail.com"
                LABEL GitHub="https://github.com/Singaravelu-web"
                LABEL BaseImage="servercore/insider:10.0.20348.1"
                LABEL RunnerVersion=${RUNNER_VERSION}

                SHELL ["powershell", "-Command", "$ErrorActionPreference = 'Stop';"]

                #Set working directory
                WORKDIR /actions-runner                
                #RUN touch abc.txt
                EOF


            - uses: game-ci/unity-builder@v2
              env:
                  UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
              with:
                  targetPlatform: ${{ matrix.targetPlatform }}
            - uses: actions/upload-artifact@v2
              with:
                  name: Build-${{ matrix.targetPlatform }}
                  path: build/${{ matrix.targetPlatform }}
